[package]
name = "rounac-uci"
version = "0.0.1"
edition = "2024"
rust-version = "1.96.0"
description = "UCI bindings used by the rounac crate."
repository = "https://github.com/rounac-crates/rounac-uci"
readme = "README.md"
license = "MIT or Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.23", features = ["serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
paste = "1.0"
iso8601 = "0.6.3"

[features]
default = ["v2_5"]
v2_5 = []

[dev-dependencies]
criterion = "0.8.2"
quick-xml = { version = "0.41.0", features = ["serialize"] }
rand = "0.10.2"
uuid = { version = "1.23", features = ["serde", "v4"] }

[[bench]]
name = "quick-xml_serde"
harness = false
